repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        stages: [commit]
        entry: poetry run mypy
        language: system
        types: [python]
      - id: ruff
        name: ruff
        stages: [commit]
        entry: poetry run ruff check
        args: [--fix]
        language: system
        types: [python]